/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.*;
import ModeloTablas.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO HUAMANJULCA G
 */
public class Frm_registrousuario extends javax.swing.JFrame {

    C_natural natural;
    C_juridico juridico;
    Cliente cliente;
    String codigo;
    String nombres;
    String apellidos;
    String Direccion;
    String t_conexion;
    String t_montaje;
    float v_conexion;
    String op_tarifaria;
    float va_tarifa;
    float precio;
    String RUC;
    String R_social;
    String nombre_representante;
    String DNI;

    /**
     * Creates new form Frm_registrousuario
     */
    public Frm_registrousuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipos_clientes = new javax.swing.ButtonGroup();
        Bg_tiposConexion = new javax.swing.ButtonGroup();
        Bg_tipoIntalacion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        Jp_tipo_conexion = new javax.swing.JPanel();
        lbl_tipo_conexion = new javax.swing.JLabel();
        Rb_mono = new javax.swing.JRadioButton();
        Rb_Bi = new javax.swing.JRadioButton();
        Rbn_tri = new javax.swing.JRadioButton();
        Jp_tipo_conexion1 = new javax.swing.JPanel();
        lbl_tipo_instalacion = new javax.swing.JLabel();
        Rb_Residencial = new javax.swing.JRadioButton();
        Rb_comercial = new javax.swing.JRadioButton();
        Rb_industrial = new javax.swing.JRadioButton();
        Rb_Especiales = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        Rb_juridico = new javax.swing.JRadioButton();
        Rb_natural = new javax.swing.JRadioButton();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        lbl_razon_social = new javax.swing.JLabel();
        lbl_nombrerepresentante = new javax.swing.JLabel();
        lbl_ruc = new javax.swing.JLabel();
        txt_RUC = new javax.swing.JTextField();
        txt_nombrerepresentante = new javax.swing.JTextField();
        Cb_razonsocial = new javax.swing.JComboBox<>();
        Bt_guardar = new javax.swing.JButton();
        Bt_nuevo = new javax.swing.JButton();
        Bt_editar = new javax.swing.JButton();
        Bt_cerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de medidores");

        txt_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_codigo.setEnabled(false);

        lbl_codigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_codigo.setText("Código: ");

        jToggleButton1.setText("Generar código");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lbl_direccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_direccion.setText("Dirección:");

        txt_direccion.setEnabled(false);

        Jp_tipo_conexion.setBackground(new java.awt.Color(153, 255, 204));

        lbl_tipo_conexion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tipo_conexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tipo_conexion.setText("Tipo de conexión");

        Bg_tiposConexion.add(Rb_mono);
        Rb_mono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_mono.setText("Monofásico");
        Rb_mono.setEnabled(false);
        Rb_mono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_monoActionPerformed(evt);
            }
        });

        Bg_tiposConexion.add(Rb_Bi);
        Rb_Bi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_Bi.setText("Bifásico");
        Rb_Bi.setEnabled(false);
        Rb_Bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_BiActionPerformed(evt);
            }
        });

        Bg_tiposConexion.add(Rbn_tri);
        Rbn_tri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rbn_tri.setText("Trifásico");
        Rbn_tri.setEnabled(false);
        Rbn_tri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbn_triActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jp_tipo_conexionLayout = new javax.swing.GroupLayout(Jp_tipo_conexion);
        Jp_tipo_conexion.setLayout(Jp_tipo_conexionLayout);
        Jp_tipo_conexionLayout.setHorizontalGroup(
            Jp_tipo_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_tipo_conexionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jp_tipo_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_tipo_conexionLayout.createSequentialGroup()
                        .addComponent(Rbn_tri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_tipo_conexionLayout.createSequentialGroup()
                        .addComponent(lbl_tipo_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_tipo_conexionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Rb_mono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Rb_Bi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        Jp_tipo_conexionLayout.setVerticalGroup(
            Jp_tipo_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_tipo_conexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tipo_conexion)
                .addGap(18, 18, 18)
                .addGroup(Jp_tipo_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_mono)
                    .addComponent(Rb_Bi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rbn_tri)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Jp_tipo_conexion1.setBackground(new java.awt.Color(153, 255, 255));

        lbl_tipo_instalacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tipo_instalacion.setText("Tipo de instalacion:");

        Bg_tipoIntalacion.add(Rb_Residencial);
        Rb_Residencial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_Residencial.setText("Residencial");
        Rb_Residencial.setEnabled(false);
        Rb_Residencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_ResidencialActionPerformed(evt);
            }
        });

        Bg_tipoIntalacion.add(Rb_comercial);
        Rb_comercial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_comercial.setText("Comercial");
        Rb_comercial.setEnabled(false);
        Rb_comercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_comercialActionPerformed(evt);
            }
        });

        Bg_tipoIntalacion.add(Rb_industrial);
        Rb_industrial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_industrial.setText("Industrial");
        Rb_industrial.setEnabled(false);
        Rb_industrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_industrialActionPerformed(evt);
            }
        });

        Bg_tipoIntalacion.add(Rb_Especiales);
        Rb_Especiales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rb_Especiales.setText("Especiales");
        Rb_Especiales.setEnabled(false);
        Rb_Especiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_EspecialesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jp_tipo_conexion1Layout = new javax.swing.GroupLayout(Jp_tipo_conexion1);
        Jp_tipo_conexion1.setLayout(Jp_tipo_conexion1Layout);
        Jp_tipo_conexion1Layout.setHorizontalGroup(
            Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_tipo_conexion1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rb_Residencial, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(Rb_industrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rb_comercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rb_Especiales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(Jp_tipo_conexion1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbl_tipo_instalacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jp_tipo_conexion1Layout.setVerticalGroup(
            Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_tipo_conexion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tipo_instalacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_comercial)
                    .addComponent(Rb_Residencial))
                .addGap(22, 22, 22)
                .addGroup(Jp_tipo_conexion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_Especiales)
                    .addComponent(Rb_industrial))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        tipos_clientes.add(Rb_juridico);
        Rb_juridico.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Rb_juridico.setText("Juridico");
        Rb_juridico.setEnabled(false);
        Rb_juridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_juridicoActionPerformed(evt);
            }
        });

        tipos_clientes.add(Rb_natural);
        Rb_natural.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Rb_natural.setText("Natural");
        Rb_natural.setEnabled(false);
        Rb_natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_naturalActionPerformed(evt);
            }
        });

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_nombre.setText("Nombres: ");

        lbl_apellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_apellidos.setText("Apellidos: ");

        lbl_dni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_dni.setText("DNI:");

        txt_nombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombres.setEnabled(false);

        txt_apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellidos.setEnabled(false);

        txt_DNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DNI.setEnabled(false);

        lbl_razon_social.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_razon_social.setText("Razón social:");

        lbl_nombrerepresentante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_nombrerepresentante.setText("Nombre del representanste:");

        lbl_ruc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ruc.setText("RUC:");

        txt_RUC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RUC.setEnabled(false);

        txt_nombrerepresentante.setEnabled(false);

        Cb_razonsocial.setEditable(true);
        Cb_razonsocial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cb_razonsocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado(a)", "Viudo(a)", "Divorsiado(a)", "Soltero(a)" }));
        Cb_razonsocial.setEnabled(false);
        Cb_razonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_razonsocialActionPerformed(evt);
            }
        });

        Bt_guardar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save_37110 (1).png"))); // NOI18N
        Bt_guardar.setText("Guardar");
        Bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_guardarActionPerformed(evt);
            }
        });

        Bt_nuevo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1486485588-add-create-new-math-sign-cross-plus_81186 (1).png"))); // NOI18N
        Bt_nuevo.setText("Nuevo");
        Bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_nuevoActionPerformed(evt);
            }
        });

        Bt_editar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_icon-icons.com_52382.png"))); // NOI18N
        Bt_editar.setText("Editar");

        Bt_cerrar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout_37127.png"))); // NOI18N
        Bt_cerrar.setText("Cerrar");
        Bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_cerrarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/customer_person_people_man_user_client_1629.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_user_customer_man_male_man_boy_people_1687.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Bt_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Bt_nuevo)
                .addGap(18, 18, 18)
                .addComponent(Bt_guardar)
                .addGap(18, 18, 18)
                .addComponent(Bt_editar))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_direccion)
                        .addGap(44, 44, 44)
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jp_tipo_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jp_tipo_conexion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Rb_juridico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_razon_social)
                        .addGap(156, 156, 156)
                        .addComponent(Cb_razonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nombrerepresentante)
                        .addGap(29, 29, 29)
                        .addComponent(txt_nombrerepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(txt_RUC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(Rb_natural, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Bt_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Bt_nuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Bt_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Bt_editar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_codigo))
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jToggleButton1)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_direccion)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Jp_tipo_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jp_tipo_conexion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Rb_juridico))
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_razon_social))
                            .addComponent(Cb_razonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombrerepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombrerepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ruc)
                            .addComponent(txt_RUC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Rb_natural))
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_apellidos))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_dni)
                            .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txt_codigo.setText(null);
        txt_direccion.setText(null);
        txt_nombrerepresentante.setText(null);
        txt_RUC.setText(null);
        txt_nombres.setText(null);
        txt_apellidos.setText(null);
        txt_DNI.setText(null);
    }

    private void activar(boolean estado) {
        txt_codigo.setEnabled(estado);
        txt_direccion.setEnabled(estado);
        Rb_juridico.setEnabled(estado);
        Rb_natural.setEnabled(estado);
    }
    private void activarRb2(boolean estado){
        Rb_mono.setEnabled(estado);
        Rb_Bi.setEnabled(estado);
        Rbn_tri.setEnabled(estado);
        Rb_Residencial.setEnabled(estado);
        Rb_comercial.setEnabled(estado);
        Rb_Especiales.setEnabled(estado);
        Rb_industrial.setEnabled(estado);
    }
    private void activarRb(boolean estado2) {
        Cb_razonsocial.setEnabled(estado2);
        txt_nombrerepresentante.setEnabled(estado2);
        txt_RUC.setEnabled(estado2);
        txt_apellidos.setEnabled(estado2);
        txt_nombres.setEnabled(estado2);
        txt_DNI.setEnabled(estado2);
    }

    private void Cb_razonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_razonsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_razonsocialActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Random r = new Random();
        int codigo;
        codigo = r.nextInt(100000);
        txt_codigo.setText(String.valueOf(codigo));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_Bt_cerrarActionPerformed

    private void Rb_juridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_juridicoActionPerformed
        Rb_natural.setEnabled(false);
        Cb_razonsocial.setEnabled(true);
        txt_nombrerepresentante.setEnabled(true);
        txt_RUC.setEnabled(true);
        txt_nombres.setEnabled(false);
        txt_apellidos.setEnabled(false);
        txt_DNI.setEnabled(false);
    }//GEN-LAST:event_Rb_juridicoActionPerformed

    private void Editables(boolean estado) {
        txt_codigo.setEditable(estado);
        txt_direccion.setEditable(estado);

    }
    private void Rb_naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_naturalActionPerformed
        Rb_juridico.setEnabled(false);
        txt_nombres.setEnabled(true);
        txt_apellidos.setEnabled(true);
        txt_DNI.setEnabled(true);
        Cb_razonsocial.setEnabled(false);
        txt_nombrerepresentante.setEnabled(false);
        txt_RUC.setEnabled(false);
    }//GEN-LAST:event_Rb_naturalActionPerformed

    private void Bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_guardarActionPerformed
        codigo = txt_codigo.getText();
        Direccion = txt_direccion.getText();
        if (Rb_mono.isSelected()) {
            t_conexion = "Monofásico";
            v_conexion = (float) 0.3;
        } else {
            if (Rb_Bi.isSelected()) {
                t_conexion = "Bifásico";
                v_conexion = (float) 0.7;
            } else {
                if (Rbn_tri.isSelected()) {
                    t_conexion = "Trifásico";
                    v_conexion = (float) 1.0;
                }
            }
        }

        if (Rb_Especiales.isSelected()) {
            op_tarifaria = "Especial";
            va_tarifa = (float) 1.0;
        } else {
            if (Rb_Residencial.isSelected()) {
                op_tarifaria = "Residecial";
                va_tarifa = (float) 0.2;
            } else {
                if (Rb_comercial.isSelected()) {
                    op_tarifaria = "Comercial";
                    va_tarifa = (float) 0.5;
                } else {
                    if (Rb_industrial.isSelected()) {
                        op_tarifaria = "Industrial";
                        va_tarifa = (float) 0.8;
                    }
                }

            }
        }
        precio = (v_conexion * va_tarifa);

        cliente = new Cliente(codigo, Direccion, t_conexion, v_conexion,
                op_tarifaria, va_tarifa, precio);
        Frm_Tabla_general.clientes.add(cliente);
        if (Rb_juridico.isSelected()) {
            R_social = String.valueOf(Cb_razonsocial.getSelectedItem());
            nombre_representante = txt_nombrerepresentante.getText();
            RUC = txt_RUC.getText();
            juridico = new C_juridico(RUC, R_social, nombre_representante,
                    codigo, Direccion, t_conexion, t_montaje,
                    v_conexion, op_tarifaria, va_tarifa, precio);
            Frm_listaJuridicos.juridicos.add(juridico);
        } else {
            if (Rb_natural.isSelected()) {
                nombres = txt_nombres.getText();
                apellidos = txt_apellidos.getText();
                DNI = txt_DNI.getText();

                natural = new C_natural(DNI, apellidos, nombres,
                        codigo, Direccion, t_conexion, t_montaje, v_conexion, op_tarifaria,
                        va_tarifa, precio);
                Frm_listanatural.naturales.add(natural);
            }
        }

        activar(false);
        activarRb(false);
        limpiar();
        JOptionPane.showMessageDialog(null, "Datos guardados exitosamente", "Guardado", 1);
        activarRb2(false);

    }//GEN-LAST:event_Bt_guardarActionPerformed

    private void Bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_nuevoActionPerformed
        txt_codigo.setEditable(false);
        limpiar();
        activar(true);
        activarRb2(true);
        txt_direccion.requestFocus();
    }//GEN-LAST:event_Bt_nuevoActionPerformed

    private void Rb_industrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_industrialActionPerformed
        Rb_comercial.setEnabled(false);
        Rb_Residencial.setEnabled(false);
        Rb_Especiales.setEnabled(false);
    }//GEN-LAST:event_Rb_industrialActionPerformed

    private void Rb_monoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_monoActionPerformed
        Rb_Bi.setEnabled(false);
        Rbn_tri.setEnabled(false);
    }//GEN-LAST:event_Rb_monoActionPerformed

    private void Rb_BiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_BiActionPerformed
        Rb_mono.setEnabled(false);
        Rbn_tri.setEnabled(false);
    }//GEN-LAST:event_Rb_BiActionPerformed

    private void Rbn_triActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbn_triActionPerformed
        Rb_Bi.setEnabled(false);
        Rb_mono.setEnabled(false);
    }//GEN-LAST:event_Rbn_triActionPerformed

    private void Rb_ResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_ResidencialActionPerformed
        Rb_comercial.setEnabled(false);
        Rb_industrial.setEnabled(false);
        Rb_Especiales.setEnabled(false);

    }//GEN-LAST:event_Rb_ResidencialActionPerformed

    private void Rb_comercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_comercialActionPerformed
        Rb_Residencial.setEnabled(false);
        Rb_industrial.setEnabled(false);
        Rb_Especiales.setEnabled(false);
    }//GEN-LAST:event_Rb_comercialActionPerformed

    private void Rb_EspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_EspecialesActionPerformed
        Rb_comercial.setEnabled(false);
        Rb_industrial.setEnabled(false);
        Rb_Residencial.setEnabled(false);
    }//GEN-LAST:event_Rb_EspecialesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_registrousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_registrousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_registrousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_registrousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_registrousuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Bg_tipoIntalacion;
    private javax.swing.ButtonGroup Bg_tiposConexion;
    private javax.swing.JButton Bt_cerrar;
    private javax.swing.JButton Bt_editar;
    private javax.swing.JButton Bt_guardar;
    private javax.swing.JButton Bt_nuevo;
    private javax.swing.JComboBox<String> Cb_razonsocial;
    private javax.swing.JPanel Jp_tipo_conexion;
    private javax.swing.JPanel Jp_tipo_conexion1;
    private javax.swing.JRadioButton Rb_Bi;
    private javax.swing.JRadioButton Rb_Especiales;
    private javax.swing.JRadioButton Rb_Residencial;
    private javax.swing.JRadioButton Rb_comercial;
    private javax.swing.JRadioButton Rb_industrial;
    private javax.swing.JRadioButton Rb_juridico;
    private javax.swing.JRadioButton Rb_mono;
    private javax.swing.JRadioButton Rb_natural;
    private javax.swing.JRadioButton Rbn_tri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombrerepresentante;
    private javax.swing.JLabel lbl_razon_social;
    private javax.swing.JLabel lbl_ruc;
    private javax.swing.JLabel lbl_tipo_conexion;
    private javax.swing.JLabel lbl_tipo_instalacion;
    private javax.swing.ButtonGroup tipos_clientes;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_RUC;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombrerepresentante;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
