/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.*;
import ModeloTablas.ModeloConsumo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO HUAMANJULCA G
 */
public class Frm_TablaConsumo extends javax.swing.JFrame {

    /**
     * Creates new form Frm_TablaConsumo
     */
    public static ArrayList<ConsumoCliente> consumos =new ArrayList<>();
    public Frm_TablaConsumo() {
        initComponents();
        Listacosumo.setModel(new ModeloConsumo(consumos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listacosumo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Bt_atras = new javax.swing.JButton();
        txt_codigo = new javax.swing.JTextField();
        Bt_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Listacosumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Consumo", "Mes", "Monto a pagar S/."
            }
        ));
        jScrollPane1.setViewportView(Listacosumo);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/electricity_3238.png"))); // NOI18N
        jLabel1.setText("Tabla de consumo");

        Bt_atras.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout_37127.png"))); // NOI18N
        Bt_atras.setText("Atrás");
        Bt_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_atrasActionPerformed(evt);
            }
        });

        Bt_buscar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Bt_buscar.setText("Buscar");
        Bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_buscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Busca y enlista datos del consumo de un cliente segun el mes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Bt_atras)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bt_buscar)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Bt_atras)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_atrasActionPerformed
        dispose();
    }//GEN-LAST:event_Bt_atrasActionPerformed

    private void Bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_buscarActionPerformed
        ConsumoCliente c=null;
         int cont = 0;
        String Dato = txt_codigo.getText();
        for (int i = 0; i < consumos.size(); i++) {
            if (Dato.equals(consumos.get(i).getCodigo())) {
                cont = i;
                c = new ConsumoCliente(consumos.get(i).getCodigo(), 
                        consumos.get(i).getMedida(), consumos.get(i).getPeriodo(),
                        consumos.get(i).getMonto_pago());

            }
            if (c == null) {
                cont = -1;
            }
        }
      
            if (cont != -1) {
                JOptionPane.showMessageDialog(null, "Usuario encontrado");
                  for (int i = 0; i < consumos.size(); i++) {
                c = new ConsumoCliente(consumos.get(i).getCodigo(), consumos.get(i).getMedida(),
                        consumos.get(i).getPeriodo(), consumos.get(i).getMonto_pago());
                JOptionPane.showMessageDialog(null, "Codigo: " + consumos.get(i).getCodigo()
                        + "\n Medidas: " + consumos.get(i).getMedida()
                        + "\n Periodo: " + consumos.get(i).getPeriodo()
                        + "\n Valor de conexion S/: " + consumos.get(i).getMonto_pago(), "Usuario", 1);
            }
                  } else {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado", "No encontrado", 0);

            }
        
        
    }//GEN-LAST:event_Bt_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TablaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TablaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TablaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TablaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_TablaConsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_atras;
    private javax.swing.JButton Bt_buscar;
    private javax.swing.JTable Listacosumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txt_codigo;
    // End of variables declaration//GEN-END:variables
}
